// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlZm9g6DnBuRr95yr5S3KniXrs4KjqdC8',
    appId: '1:289343347265:web:a7010b9f31784902b984c0',
    messagingSenderId: '289343347265',
    projectId: 'physic-lab-app',
    authDomain: 'physic-lab-app.firebaseapp.com',
    storageBucket: 'physic-lab-app.firebasestorage.app',
    measurementId: 'G-MRFMZEQ0PE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLSyrucMjXGkv_I3h-QGNm0Ekk9PxtZwo',
    appId: '1:289343347265:android:d9ba6a16881aeef2b984c0',
    messagingSenderId: '289343347265',
    projectId: 'physic-lab-app',
    storageBucket: 'physic-lab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXp68FrmfpFL-xYcBzCKGcbwfy4_9FPRQ',
    appId: '1:289343347265:ios:57ec50ee12d0e0b1b984c0',
    messagingSenderId: '289343347265',
    projectId: 'physic-lab-app',
    storageBucket: 'physic-lab-app.firebasestorage.app',
    iosBundleId: 'com.example.physicLabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXp68FrmfpFL-xYcBzCKGcbwfy4_9FPRQ',
    appId: '1:289343347265:ios:57ec50ee12d0e0b1b984c0',
    messagingSenderId: '289343347265',
    projectId: 'physic-lab-app',
    storageBucket: 'physic-lab-app.firebasestorage.app',
    iosBundleId: 'com.example.physicLabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlZm9g6DnBuRr95yr5S3KniXrs4KjqdC8',
    appId: '1:289343347265:web:fb4036d61c2b5ceab984c0',
    messagingSenderId: '289343347265',
    projectId: 'physic-lab-app',
    authDomain: 'physic-lab-app.firebaseapp.com',
    storageBucket: 'physic-lab-app.firebasestorage.app',
    measurementId: 'G-PEW22GDY91',
  );
}
